import { Message } from "@/app/services/conversations";
import { renderMarkdownToHTML, generatePDFHTML, createSafeFilename } from "@/app/utils/downloadUtils";
import { useTranslation } from "@/app/contexts/TranslationContext";

interface ReportData {
  lastAssistantMessage: Message;
  userQuery: string;
  safeFilename: string;
}

export function useDownloadReport(messages: Message[]) {
  const { t } = useTranslation();

  const getReportData = (): ReportData | null => {
    let lastAssistantIndex = -1;
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i].role === "assistant") {
        lastAssistantIndex = i;
        break;
      }
    }

    if (lastAssistantIndex === -1) return null;

    const lastAssistantMessage = messages[lastAssistantIndex];

    let userQuery = "security-assessment";
    for (let i = lastAssistantIndex - 1; i >= 0; i--) {
      if (messages[i].role === "user") {
        userQuery = messages[i].content;
        break;
      }
    }

    const safeFilename = createSafeFilename(userQuery);

    return {
      lastAssistantMessage,
      userQuery,
      safeFilename,
    };
  };

  const downloadMarkdown = () => {
    const reportData = getReportData();
    if (!reportData) return;

    const { lastAssistantMessage, userQuery, safeFilename } = reportData;

    const fileContent = `# Security Assessment Report

**Tool:** ${userQuery}
**Generated by:** ToolSense AI
**Date:** ${new Date().toLocaleString()}

---

${lastAssistantMessage.content}
`;

    const blob = new Blob([fileContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${safeFilename}-${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const downloadPDF = async () => {
    const reportData = getReportData();
    if (!reportData) return;

    const { lastAssistantMessage, userQuery } = reportData;

    const renderedContent = await renderMarkdownToHTML(lastAssistantMessage.content);
    const htmlContent = generatePDFHTML(userQuery, renderedContent);

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert(t("chatbot.popupBlocked"));
      return;
    }

    printWindow.document.write(htmlContent);
    printWindow.document.close();

    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        setTimeout(() => {
          printWindow.close();
        }, 100);
      }, 250);
    };
  };

  return { downloadMarkdown, downloadPDF };
}

